### ISSUE TITLE
luape will not compile a label eg ::help:: 

### ISSUE THREAD

**Issue by pfaber11** [rosemash/luape#1]
When I try to create a label it throws up an error . tried lua 5.3 and 5.1  and the same thing happens . If I take out the goto and label it compiles fine . My little program works fine in the zerobrane IDE . Is there an older version of luape I could try.

**Comment by pfaber11** [comment]
I have tried an earlier version or luape.exe and still the same problem . I'm using windows 11 but I don't think that is the `problem.`
`

**Comment by rosemash** [comment]
luape is compiled with Lua 5.1, but labels and the goto statement were introduced in Lua 5.2. If you want to use those features in luape, you will have to replace Lua 5.1 source with Lua 5.2 source in the `deps` directory and recompile luape.

The version of Lua 5.1 already included has been slightly modified in order to support luape's options and flags. You will have to add those changes to the Lua 5.2 source before compiling or options like `/debug` won't work (all builds will be debug builds).

**Comment by pfaber11** [comment]
Thankyou very much for the explanation I will try to recompile Luape with 5.2 + and see how I get on . Awesome tool none the less. Thanks. Sent from Mail for Windows From: rosemashSent: 11 April 2022 19:48To: rosemash/luapeCc: pfaber11; AuthorSubject: Re: [rosemash/luape] luape will not compile a label eg ::help:: (Issue #1) luape is compiled with Lua 5.1, but labels and goto were introduced in Lua 5.2. If you want to use those features in luape, you will have to replace Lua 5.1 source with Lua 5.2 source in the deps directory and recompile luape.The version of Lua 5.1 already included has been slightly modified in order to support luape's options and flags. You will have to add those changes to the Lua 5.2 source before compiling or options like /debug won't work (all builds will be debug builds).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
